core/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('productos/', views.productos, name='productos'),
    path('contacto/', views.contacto, name='contacto'),
    path('colaborador_login/', views.colaborador_login, name='colaborador_login'),
    path('cliente_login/', views.cliente_login, name='cliente_login'),
    path('bodeguero_login/', views.bodeguero_login, name='bodeguero_login'),
    path('contador_login/', views.contador_login, name='contador_login'),
    path('register/', views.register, name='register'),
    path('agregar_al_carrito/<int:producto_id>/', views.agregar_al_carrito, name='agregar_al_carrito'),
    path('eliminar_del_carrito/<int:item_id>/', views.eliminar_del_carrito, name='eliminar_del_carrito'),
    path('ver_carrito/', views.ver_carrito, name='ver_carrito'),
    path('producto/<int:producto_id>/', views.product_detail, name='product_detail'),
    path('checkout/', views.checkout, name='checkout'),
    path('tareas/', views.listar_tareas, name='listar_tareas'),
    path('tareas/crear/', views.crear_tarea, name='crear_tarea'),
    path('tareas/<int:tarea_id>/editar/', views.editar_tarea, name='editar_tarea'),
    path('tareas/<int:tarea_id>/eliminar/', views.eliminar_tarea, name='eliminar_tarea'),
    path('clientes/', views.listar_clientes, name='listar_clientes'),
    path('clientes/crear/', views.crear_cliente, name='crear_cliente'),
    path('clientes/<int:cliente_id>/editar/', views.editar_cliente, name='editar_cliente'),
    path('pago_iniciar/', views.pago_iniciar, name='pago_iniciar'),
    path('pago_exito/', views.pago_exito, name='pago_exito'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
# mysite/urls.py
from django.contrib import admin # type: ignore
from django.urls import path, include # type: ignore

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),  # Incluye las rutas de la aplicación core
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

from mysite import settings

class Marca(models.Model):
    nombre = models.CharField(max_length=255, default='Marca Predeterminada')

    def __str__(self):
        return self.nombre

class TipoProducto(models.Model):
    nombre = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    Nombre = models.CharField(max_length=255)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    imagen = models.ImageField(upload_to='producto', null=True)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    tipo = models.ForeignKey(TipoProducto, on_delete=models.CASCADE)

    def __str__(self):
        return self.Nombre

class CarritoItem(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)
    añadido_el = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.cantidad} x {self.producto.Nombre}'

class Tarea(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=200)
    descripcion = models.TextField(blank=True, null=True)
    completada = models.BooleanField(default=False)
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titulo
    
class Cliente(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    direccion = models.CharField(max_length=255)
    telefono = models.CharField(max_length=15)
    fecha_nacimiento = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.user.username

#PROCESOS
class Pedido(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    estado = models.CharField(max_length=20, default='pendiente')
    fecha = models.DateTimeField(auto_now_add=True)

class PedidoItem(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    producto = models.ForeignKey('Producto', on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)

class Boleta(models.Model):
    id_boleta = models.CharField(max_length=20, primary_key=True)
    cliente = models.CharField(max_length=100)
    monto = models.DecimalField(max_digits=10, decimal_places=2)
    fecha = models.DateField()

    def __str__(self):
        return f"{self.id_boleta} - {self.cliente}"

#INFO
opciones_motivos = [
    [0, "reclamo"],
    [1, "sugerencia"],
    [2, "ayuda"],
]

class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    rut = models.CharField(max_length=10)
    motivo = models.IntegerField(choices=opciones_motivos)
    mensaje = models.TextField()
    
    def __str__(self):
        return self.nombre

#transaccion
class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    buy_order = models.CharField(max_length=255)
    session_id = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=50)
    authorization_code = models.CharField(max_length=50)
    transaction_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Transaction {self.buy_order} - {self.status}"

core/forms.py
# forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Cliente, Producto, Tarea

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30, required=False, help_text='Opcional')
    last_name = forms.CharField(max_length=30, required=False, help_text='Opcional')

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

class TareaForm(forms.ModelForm):
    class Meta:
        model = Tarea
        fields = ['titulo', 'descripcion', 'completada']

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['direccion', 'telefono', 'fecha_nacimiento']

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = '__all__'
        
#class BoletaForm(forms.ModelForm):
#    class Meta:
#        model = Boleta
#        fields = ['id_boleta', 'cliente', 'monto', 'fecha']

core/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages
import requests
from .forms import ClienteForm, UserRegisterForm, TareaForm
from .models import Cliente, Pedido, PedidoItem, Producto, CarritoItem, Tarea
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from transbank.webpay.webpay_plus.transaction import Transaction
from transbank.webpay.webpay_plus.transaction import Transaction as WebpayTransaction
from .models import Transaction

# Páginas principales
def home(request):
    return render(request, 'core/home.html')

def about(request):
    return render(request, 'core/about.html')

def contacto(request):
    return render(request, 'core/contacto.html')

# Autenticación de usuarios
def colaborador_login(request):
    return render(request, 'core/colaborador_login.html')

def cliente_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Usuario o contraseña incorrectos')
    return render(request, 'core/cliente_login.html')

def bodeguero_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Usuario o contraseña incorrectos')
    return render(request, 'core/bodeguero_login.html')

def contador_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Usuario o contraseña incorrectos')
    return render(request, 'core/contador_login.html')

@csrf_protect
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            Cliente.objects.create(user=user)  # Crear Cliente asociado al usuario
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f'Cuenta creada para {username}')
                return redirect('home')
            else:
                messages.error(request, 'Ocurrió un problema al autenticar el usuario.')
        else:
            print(form.errors)  # Añadir esto para ver los errores del formulario en la consola
            messages.error(request, 'Corrige los errores en el formulario')
    else:
        form = UserRegisterForm()
    return render(request, 'core/register.html', {'form': form})

# Gestión del carrito
@login_required
def agregar_al_carrito(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)
    carrito_item, created = CarritoItem.objects.get_or_create(producto=producto)
    if not created:
        carrito_item.cantidad += 1
    carrito_item.save()
    return redirect('ver_carrito')

@login_required
def eliminar_del_carrito(request, item_id):
    carrito_item = get_object_or_404(CarritoItem, id=item_id)
    carrito_item.delete()
    return redirect('ver_carrito')

@login_required
def ver_carrito(request):
    carrito_items = CarritoItem.objects.all()
    return render(request, 'core/ver_carrito.html', {'carrito_items': carrito_items})

@login_required
def checkout(request):
    carrito_items = CarritoItem.objects.all()
    total = sum(item.producto.precio * item.cantidad for item in carrito_items)
    return render(request, 'core/checkout.html', {'carrito_items': carrito_items, 'total': total})

@login_required
def procesar_pago(request):
    if request.method == 'POST':
        nombre = request.POST.get('nombre')
        direccion = request.POST.get('direccion')
        telefono = request.POST.get('telefono')
        email = request.POST.get('email')
        tarjeta = request.POST.get('tarjeta')
        expiracion = request.POST.get('expiracion')
        cvv = request.POST.get('cvv')
        
        messages.success(request, 'Pago procesado correctamente')
        
        return redirect('pago_exitoso')
    
    return redirect('checkout')

@login_required
def pago_exitoso(request):
    return render(request, 'core/pago_exitoso.html')

# Gestión de productos
def productos(request):
    productos = Producto.objects.all()
    return render(request, 'core/productos.html', {'productos': productos})

def product_detail(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)
    return render(request, 'core/product_detail.html', {'producto': producto})

# Gestión de tareas
@login_required
def listar_tareas(request):
    tareas = Tarea.objects.filter(usuario=request.user)
    return render(request, 'core/listar_tareas.html', {'tareas': tareas})

@login_required
def crear_tarea(request):
    if request.method == 'POST':
        form = TareaForm(request.POST)
        if form.is_valid():
            tarea = form.save(commit=False)
            tarea.usuario = request.user
            tarea.save()
            messages.success(request, 'Tarea creada con éxito')
            return redirect('listar_tareas')
    else:
        form = TareaForm()
    return render(request, 'core/crear_tarea.html', {'form': form})

@login_required
def editar_tarea(request, tarea_id):
    tarea = get_object_or_404(Tarea, id=tarea_id, usuario=request.user)
    if request.method == 'POST':
        form = TareaForm(request.POST, instance=tarea)
        if form.is_valid():
            form.save()
            messages.success(request, 'Tarea actualizada con éxito')
            return redirect('listar_tareas')
    else:
        form = TareaForm(instance=tarea)
    return render(request, 'core/editar_tarea.html', {'form': form})

@login_required
def eliminar_tarea(request, tarea_id):
    tarea = get_object_or_404(Tarea, id=tarea_id, usuario=request.user)
    if request.method == 'POST':
        tarea.delete()
        messages.success(request, 'Tarea eliminada con éxito')
        return redirect('listar_tareas')
    return render(request, 'core/eliminar_tarea.html', {'tarea': tarea})

# Gestión de clientes
@login_required
def crear_cliente(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            cliente = form.save(commit=False)
            cliente.user = request.user
            cliente.save()
            messages.success(request, 'Cliente creado con éxito')
            return redirect('listar_clientes')
    else:
        form = ClienteForm()
    return render(request, 'core/crear_cliente.html', {'form': form})

@login_required
def editar_cliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, id=cliente_id)
    if request.method == 'POST':
        form = ClienteForm(request.POST, instance=cliente)
        if form.is_valid():
            form.save()
            messages.success(request, 'Cliente actualizado con éxito')
            return redirect('listar_clientes')
    else:
        form = ClienteForm(instance=cliente)
    return render(request, 'core/editar_cliente.html', {'form': form})

@login_required
def listar_clientes(request):
    clientes = Cliente.objects.all()
    return render(request, 'core/listar_clientes.html', {'clientes': clientes})

    add_form = ProductoForm()

    return render(request, 'app/CRUD/bodeguero.html', {
        'pedidos': pedidos,
        'productos': productos,
        'form': form,
        'edit_producto_id': edit_producto_id,
        'add_form': add_form,
        'marcas': marcas,
    })

def contador(request):
    if request.method == 'POST':
        form = BoletaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('contador')
    else:
        form = BoletaForm()
    boletas = boletas.objects.all()
    return render(request, 'app/CRUD/contador.html', {'form': form, 'boletas': boletas})

def ingreso_boletas(request):
    if request.method == 'POST':
        form = BoletaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('contador')
    else:
        form = BoletaForm() # type: ignore
    return render(request, 'app/CRUD/contador.html', {'form': form})

def pago_iniciar(request):
    # Obtén el carrito del usuario con estado 'pendiente'
    carrito_items = CarritoItem.objects.all()

    # Calcula el total del carrito
    total = sum(item.producto.precio * item.cantidad for item in carrito_items)
    
    # Redondea el total a un entero
    total = int(total)

    # Configura la transacción de Webpay
    tx = WebpayTransaction()
    response = tx.create(
        buy_order=str(request.user.id) + str(carrito_items.first().id),
        session_id=request.session.session_key,
        amount=total,
        return_url="http://127.0.0.1:8000/pago_exito/"
    )

    if request.method == 'POST':
        # Crear el pedido después de confirmar el pago
        pedido = Pedido.objects.create(user=request.user, total=total)
        for item in carrito_items:
            PedidoItem.objects.create(
                pedido=pedido,
                producto=item.producto,
                cantidad=item.cantidad,

core/templates/CRUD/bodeguero.html
{% extends "app/base.html" %}
{% load static %}

{% block contenido_fh %}
<style>
    body {
        background-color: #f4f4f4;
    }

    .container-bodeguero {
        background-color: #fff;
        border-radius: 10px;
        padding: 20px;
        margin-top: 20px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .header img {
        border-radius: 50%;
    }

    .header .user-info {
        margin-left: 20px;
    }

    .header .user-info h1, .header .user-info p {
        margin: 0;
    }

    .btn-modify {
        background-color: #007bff;
        color: #fff;
    }

    .btn-accept {
        background-color: #28a745;
        color: #fff;
    }

    .btn-cancel {
        background-color: #dc3545;
        color: #fff;
    }

    .pagination .page-link {
        color: #333;
    }

    .pagination .active .page-link {
        background-color: #333;
        border-color: #333;
        color: #fff;
    }

    .modal-centered .modal-dialog {
        display: flex;
        justify-content: center;
        align-items: center;
    }
    
    .modal-centered .modal-content {
        width: 100%;
        max-width: 500px;
    }
</style>

<div class="container-bodeguero">
    <div class="d-flex align-items-center header mb-4">
        <img src="https://via.placeholder.com/100" alt="Imagen del usuario" width="100" height="100">
        <div class="user-info">
            <h1>Mario Hugo</h1>
            <p>Bodeguero</p>
            <p>ID: 00018</p>
        </div>
    </div>
    <div class="d-flex justify-content-between mb-4">
        <button class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#addModal">Agregar Producto</button>
    </div>
    <div class="table-responsive mb-4">
        <div class="section-background">
            <h1 style="text-align:center; font-size:2em;">Pedidos</h1>
        </div>
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Nombre cliente</th>
                    <th>Producto</th>
                    <th>Precio</th>
                    <th>Modificar</th>
                    <th>Estado del Pedido</th>
                </tr>
            </thead>
            <tbody>
                {% for pedido in pedido %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ pedido.user.username }}</td>
                    <td>
                        <ul>
                            {% for item in pedido.pedidoitem_set.all %}
                            <li>{{ item.producto.nombre }} ({{ item.cantidad }})</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>${{ pedido.total }}</td>
                    <td><button class="btn btn-modify">Modificar</button></td>
                    <td>
                        <button class="btn btn-accept">Aceptar</button>
                        <button class="btn btn-cancel">Cancelar</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="table-responsive">
        <div class="section-background">
            <h1 style="text-align:center; font-size:2em;">Productos</h1>
        </div>
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Marca</th>
                    <th>Precio</th>
                    <th>Modificar</th>
                    <th>Eliminar</th>
                </tr>
            </thead>
            <tbody>
                {% for producto in productos %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ producto.nombre }}</td>
                    <td>{{ producto.marca.nombre }}</td>
                    <td>${{ producto.precio }}</td>
                    <td>
                        <button class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#editModal"
                            data-id="{{ producto.id }}"
                            data-nombre="{{ producto.nombre }}"
                            data-marca="{{ producto.marca.id }}"
                            data-precio="{{ producto.precio }}"
                            data-codigo="{{ producto.codigo }}"
                            data-descripcion="{{ producto.descripcion }}">Modificar</button>
                    </td>
                    <td>
                        <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal" data-id="{{ producto.id }}">Eliminar</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">&laquo; Anterior</a>
            </li>
            <li class="page-item active"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item">
                <a class="page-link" href="#">Siguiente &raquo;</a>
            </li>
        </ul>
    </nav>
</div>

<!-- Modal para agregar producto -->
<div class="modal fade modal-centered" id="addModal" tabindex="-1" aria-labelledby="addModalLabel" aria-hidden="true">
<div class="modal-dialog">
    <div class="modal-content">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" name="add-product" value="add-product">
            <div class="modal-header">
                <h5 class="modal-title" id="addModalLabel">Agregar Producto</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label for="add_nombre" class="form-label">Nombre</label>
                    <input type="text" class="form-control" id="add_nombre" name="nombre">
                </div>
                <div class="mb-3">
                    <label for="add_marca" class="form-label">Marca</label>
                    <select class="form-control" id="add_marca" name="marca">
                        {% for marca in marcas %}
                        <option value="{{ marca.id }}">{{ marca.nombre }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="mb-3">
                    <label for="add_precio" class="form-label">Precio</label>
                    <input type="number" class="form-control" id="add_precio" name="precio">
                </div>
                <div class="mb-3">
                    <label for="add_codigo" class="form-label">Código</label>
                    <input type="number" class="form-control" id="add_codigo" name="codigo">
                </div>
                <div class="mb-3">
                    <label for="add_descripcion" class="form-label">Descripción</label>
                    <textarea class="form-control" id="add_descripcion" name="descripcion"></textarea>
                </div>
                <div class="mb-3">
                    <label for="add_imagen" class="form-label">Imagen</label>
                    <input type="file" class="form-control" id="add_imagen" name="imagen">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary">Guardar Producto</button>
            </div>
        </form>
    </div>
</div>
</div>

<!-- Modal para modificar producto -->
<div class="modal fade modal-centered" id="editModal" tabindex="-1" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog">
    <div class="modal-content">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" name="edit-product" value="edit-product">
            <input type="hidden" name="edit_producto_id" id="edit_producto_id">
            <div class="modal-header">
                <h5 class="modal-title" id="editModalLabel">Modificar Producto</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label for="edit_nombre" class="form-label">Nombre</label>
                    <input type="text" class="form-control" id="edit_nombre" name="nombre">
                </div>
                <div class="mb-3">
                    <label for="edit_marca" class="form-label">Marca</label>
                    <select class="form-control" id="edit_marca" name="marca">
                        {% for marca in marcas %}
                        <option value="{{ marca.id }}">{{ marca.nombre }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="mb-3">
                    <label for="edit_precio" class="form-label">Precio</label>
                    <input type="number" class="form-control" id="edit_precio" name="precio">
                </div>
                <div class="mb-3">
                    <label for="edit_codigo" class="form-label">Código</label>
                    <input type="number" class="form-control" id="edit_codigo" name="codigo">
                </div>
                <div class="mb-3">
                    <label for="edit_descripcion" class="form-label">Descripción</label>
                    <textarea class="form-control" id="edit_descripcion" name="descripcion"></textarea>
                </div>
                <div class="mb-3">
                    <label for="edit_imagen" class="form-label">Imagen</label>
                    <input type="file" class="form-control" id="edit_imagen" name="imagen">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary">Guardar cambios</button>
            </div>
        </form>
    </div>
</div>
</div>

<!-- Modal para eliminar producto -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
<div class="modal-dialog">
    <div class="modal-content">
        <form method="POST">
            {% csrf_token %}
            <input type="hidden" name="delete-product" value="delete-product">
            <input type="hidden" name="delete_producto_id" id="delete_producto_id">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Eliminar Producto</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>¿Está seguro que desea eliminar este producto?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="submit" class="btn btn-danger">Eliminar</button>
            </div>
        </form>
    </div>
</div>
</div>

{% endblock %}

{% block scripts %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var deleteModal = document.getElementById('deleteModal');
        deleteModal.addEventListener('show.bs.modal', function(event) {
            var button = event.relatedTarget;
            var productoId = button.getAttribute('data-id');
            var inputProductoId = document.getElementById('delete_producto_id');
            inputProductoId.value = productoId;
        });

        var editModal = document.getElementById('editModal');
    editModal.addEventListener('show.bs.modal', function(event) {
        var button = event.relatedTarget;
        var productoId = button.getAttribute('data-id');
        var nombre = button.getAttribute('data-nombre');
        var marca = button.getAttribute('data-marca');
        var precio = button.getAttribute('data-precio');
        var codigo = button.getAttribute('data-codigo');
        var descripcion = button.getAttribute('data-descripcion');

        console.log("Producto ID:", productoId);
        console.log("Nombre:", nombre);
        console.log("Marca:", marca);
        console.log("Precio:", precio);
        console.log("Código:", codigo);
        console.log("Descripción:", descripcion);

        var inputProductoId = document.getElementById('edit_producto_id');
        var inputNombre = document.getElementById('edit_nombre');
        var inputMarca = document.getElementById('edit_marca');
        var inputPrecio = document.getElementById('edit_precio');
        var inputCodigo = document.getElementById('edit_codigo');
        var inputDescripcion = document.getElementById('edit_descripcion');

        inputProductoId.value = productoId;
        inputNombre.value = nombre;
        inputMarca.value = marca;
        inputPrecio.value = precio;
        inputCodigo.value = codigo;
        inputDescripcion.value = descripcion;
    });
    });
</script>
{% endblock %}